daemon off;
pid /tmp/h5ai/nginx.pid;
worker_processes auto;
events {
    worker_connections 768;
}
error_log /proc/self/fd/2 warn;

http {
    access_log /proc/self/fd/1;

    client_body_temp_path /tmp/h5ai/client_body;
    proxy_temp_path /tmp/h5ai/proxy;
    fastcgi_temp_path /tmp/h5ai/fastcgi;
    uwsgi_temp_path /tmp/h5ai/uwsgi;
    scgi_temp_path /tmp/h5ai/scgi;

    gzip on;
    server_tokens off;

    include mime.types;

    server {
        listen 8080;
        server_name _;
        root /app;
        charset utf-8;

        auth_basic "auth";
        auth_basic_user_file /tmp/h5ai/htpasswd;

        index /_h5ai/public/index.php;

        location / {
            try_files $uri $uri/ /_h5ai/public/index.php?$args;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass unix:/tmp/h5ai/php-fpm.sock;
        }

        location ^~ /_h5ai/private/ { deny all; }
    }
}
